Updated dot and colon overrides, fixes to module management

diff --git a/csgo-server b/csgo-server
--- a/csgo-server
+++ b/csgo-server
@@ -35,7 +35,7 @@ EOF
 
 
 
-################################### PROGRAM ###################################
+################################# DEFINITIONS ##################################
 
 
 # Get script filename and directory
@@ -53,32 +53,53 @@ USER_DIR="$HOME/msm.d"
 
 
 # override dot builtin: execute a handler (either a .sh-file or .sh-files in a directory)
+# Further parameters are passed to the executed scripts
 . () {
-	local cmd=${1%%.*} # Strip file extension
-	shift
-	.file "$cmd.sh" $@ || .dir "$cmd" $@
+	local cmd=${1%%.sh} # Strip .sh extension
+	shift               # Makes ${@:2} unnecessary
+	# Try executing file or file.sh (depending on extension) otherwise execute sh-files in directory
+	if [[ $cmd =~ \.[^/]*$ ]]
+		then .file "$cmd" $@ && return
+		else .file "$cmd.sh" $@ && return; fi
+	.dir "$cmd" $@
 }
 
+
+# Execute all .sh-files inside a given directory
+# Further parameters are passed to the executed scripts
+#
+# Fails and exits if any file is faulty or no files exist in the directory
 .dir () {
-	[[ -d $1 ]] && { for file in "$1"/*.sh; do .file "$file" ${@:2}; done; }
+	[[ -d $1 ]] && {								\
+		for file in "$1"/*.sh; do					\
+			.file "$file" ${@:2} || return 1; done; \
+		}
 }
 
+
+# Execute a file and set the context for the colon function
+# Further parameters are passed to the executed scripts
 .file () {
 	local currentSrcDir="$(dirname $1)"
 	[[ -f $1 ]] && builtin . "$1" ${@:2}
 }
 
+
 # override colon builtin: execute a file relative to the current file's base directory
-: () {
-	local oldSrcDir="$currentSrcDir"
-	local currentSrcDir="$oldSrcDir/$(dirname "$1")"
-	builtin . "$oldSrcDir/$1"
-}
+# Further parameters are passed to the executed scripts
+: () { . $currentSrcDir/$1 ${@:2}; }
 
 
 
-. defaults.conf
-. program/main.sh $@
+
+################################### PROGRAM ####################################
+
+
+# This sets the default parameters such as $APP, if not given through the environment
+. "$USER_DIR/defaults.conf" || . "$THIS_DIR/defaults.conf"
+
+# Run the thing
+. "$THIS_DIR/program" $@
 
 
 
