Removed $SU variable, removed some unnecessary quotes
The user switching now always uses sudo -u $TARGET_USER $COMMAND.

diff --git a/csgo-server b/csgo-server
--- a/csgo-server
+++ b/csgo-server
@@ -75,11 +75,6 @@ EOF
 
 ########################### BASIC SCRIPT CONFIGURATION ###########################
 
-# Select user switch command (su or sudo)
-# Note: `sudo -u USER command' would be greater, but takes more work
-SU="sudo su -"
-# SU="su -"
-
 # APPID, APPNAME: Steam App ID an name of the game to be managed
 APPID=740
 APPNAME="csgo"
@@ -100,21 +95,21 @@ start () {
 	echo "Starting $SERVER_TEXT ..."
 	# Nothing to do if server is already running
 	if status; then catinfo <<-EOF
-			$(bold "INFO:")  $SERVER_TEXT is already running!
+			$(bold INFO:)  $SERVER_TEXT is already running!
 			       Enter the console using '$THIS_COMM @$INSTANCE console'.
 
 			EOF
 		return 0; fi
 
 	if [[ ! -d $INSTANCE_DIR ]]; then caterr <<-EOF
-			$(bold "ERROR:") Instance directory $(bold "$INSTANCE_DIR") does not exist!
+			$(bold ERROR:) Instance directory $(bold "$INSTANCE_DIR") does not exist!
 			       Create an instance using '$THIS_COMM @$INSTANCE create-instance'.
 
 			EOF
 		return 1; fi
 
 	if [[ ! -w $INSTANCE_DIR ]]; then caterr <<-EOF
-			$(bold "ERROR:") You do not have full access to $(bold "$INSTANCE_DIR")!
+			$(bold ERROR:) You do not have full access to $(bold "$INSTANCE_DIR")!
 			       Only $(bold "$ADMIN") can modify and launch the base installation! Try creating
 			       an own instance using '$THIS_COMM @name create-instance' instead.
 
@@ -122,7 +117,7 @@ start () {
 		return 1; fi
 
 	if [[ ! -x $INSTANCE_DIR/$SERVER_EXEC ]]; then caterr <<-EOF
-			$(bold "ERROR:") Server Executable not found at $(bold "$INSTANCE_DIR/$SERVER_EXEC")!
+			$(bold ERROR:) Server Executable not found at $(bold "$INSTANCE_DIR/$SERVER_EXEC")!
 			       Try repairing the installation using '$THIS_COMM update',
 			       '$THIS_COMM repair' or re-create this instance.
 
@@ -160,7 +155,7 @@ status () {
 	if [[ ! -e "$SOCKET" ]]; then return 1; fi
 
 	if [[ ! -w "$SOCKET" ]]; then caterr <<-EOF
-			$(bold "ERROR:") Cannot access tmux socket of $SERVER_TEXT!
+			$(bold ERROR:) Cannot access tmux socket of $SERVER_TEXT!
 
 			EOF
 		return 23; fi # 23 = access error
@@ -178,7 +173,7 @@ status () {
 # Switch to the game console in tmux session
 console () {
 	if ! status; then caterr <<-EOF
-			$(bold "ERROR:") $SERVER_TEXT is not running
+			$(bold ERROR:) $SERVER_TEXT is not running
 
 			EOF
 		return 1; fi
@@ -197,9 +192,9 @@ update () {
 			Only the admin $(bold "$ADMIN") can $ACTION the base installation.
 			Please log in to the account of $(bold "$ADMIN") now! (or CTRL-D to cancel)
 			EOF
-		$SU "$ADMIN" -c "'$THIS_SCRIPT' $ACTION"
+		sudo -i -u "$ADMIN" "$THIS_SCRIPT" "$ACTION"
 		if (( $? )); then caterr <<-EOF
-				$(bold "ERROR:") Installation/update as $(bold "$ADMIN") failed!
+				$(bold ERROR:) Installation/update as $(bold "$ADMIN") failed!
 
 				EOF
 			return 1; fi
@@ -220,17 +215,17 @@ update () {
 			)
 
 		if (( $? )); then caterr <<-EOF
-				$(bold "ERROR:") Searching for updates failed!
+				$(bold ERROR:) Searching for updates failed!
 
 				EOF
 			return 1; fi
 		if [[ $(cat "$APPMANIFEST" | grep "buildid" | awk '{ print $2 }' 2>/dev/null) == $buildid ]]; then
 			# No update is necessary
-			catinfo <<< "$(bold "INFO:")  The base installation is already up to date."
+			catinfo <<< "$(bold INFO:)  The base installation is already up to date."
 			echo
 			return 0; fi
 
-		catinfo <<< "$(bold "INFO:")  An update for the base installation is available."
+		catinfo <<< "$(bold INFO:)  An update for the base installation is available."
 		echo
 
 		touch "$INSTALL_DIR/msm.d/updating"
@@ -271,11 +266,11 @@ update () {
 
 	unset try tries
 	if [[ $SUCCESS ]]; then
-		catinfo <<< "$(bold "INFO:")  Update completed successfully!"
+		catinfo <<< "$(bold INFO:)  Update completed successfully!"
 		echo
 		return 0
 	else catwarn <<-EOF
-		$(bold "WARN:")  Update failed! For more information, see the log file"
+		$(bold WARN:)  Update failed! For more information, see the log file"
 		       at $(bold "$LOGFILE")."
 
 		EOF
@@ -293,14 +288,14 @@ check-instance-dir () {
 	[[ -e $INSTANCE_DIR ]] && {
 		if ! [[ -d $INSTANCE_DIR ]]; then
 			caterr <<-EOF
-				$(bold "ERROR:") $(bold "$INSTANCE_DIR") is not a directory! Move the file and try again.
+				$(bold ERROR:) $(bold "$INSTANCE_DIR") is not a directory! Move the file and try again.
 
 				EOF
 			return 23; fi
 
 		if ! [[ -r $INSTANCE_DIR && -w $INSTANCE_DIR && -x $INSTANCE_DIR ]]; then
 			caterr <<-EOF
-				$(bold "ERROR:") You do not have the necessary privileges to create a server instance
+				$(bold ERROR:) You do not have the necessary privileges to create a server instance
 				       in $(bold "$INSTANCE_DIR")!
 
 				EOF
@@ -310,7 +305,7 @@ check-instance-dir () {
 		
 		if ! [[ $(cat $INSTANCE_DIR/msm.d/appid 2> /dev/null) == $APPID ]]; then
 			catwarn <<-EOF
-				$(bold "WARN:")  The directory $(bold "$INSTANCE_DIR") already contains data,
+				$(bold WARN:)  The directory $(bold "$INSTANCE_DIR") already contains data,
 				       which may or may not be game server data. Please backup any important
 				       files before proceeding!
 
@@ -319,7 +314,7 @@ check-instance-dir () {
 
 		if ! [[ -e $INSTANCE_DIR/msm.d/is-admin ]]; then # Is an instance, but not an admin
 			catwarn <<-EOF
-				$(bold "WARN:")  A game instance already exists at $(bold "$INSTANCE_DIR").
+				$(bold WARN:)  A game instance already exists at $(bold "$INSTANCE_DIR").
 				       Please backup any important files before proceeding!
 
 				EOF
@@ -358,7 +353,7 @@ create-instance () {
 		EOF
 
 	if [[ ! $INSTANCE ]]; then catinfo <<-EOF
-		$(bold "INFO:")  You have selected a base installation, There is no need to create an
+		$(bold INFO:)  You have selected a base installation, There is no need to create an
 		       instance here. If you want to create a new instance, set the instance
 		       name using '$THIS_COMM @name create'.
 
@@ -393,7 +388,7 @@ create-instance () {
 
 	if (( $? )); then
 		caterr <<-EOF
-			$(bold "ERROR:") An error occured while executing the instance creation script!
+			$(bold ERROR:) An error occured while executing the instance creation script!
 
 			EOF
 		rm -rf "$INSTANCE_DIR" > /dev/null 2>&1
@@ -406,7 +401,7 @@ create-instance () {
 
 	if ! symlink-all-files; then
 		caterr <<-EOF
-			$(bold "ERROR:") Linking this instance to the base installation failed.
+			$(bold ERROR:) Linking this instance to the base installation failed.
 
 			EOF
 		rm -rf "$INSTANCE_DIR" > /dev/null 2>&1
@@ -440,16 +435,16 @@ echo # Make some space
 
 # Detect if this has been called via source command
 if [[ $0 != ${BASH_SOURCE[0]} ]]; then
-	echo "$(bold "INFO:")  This script has been invoked using the 'source' builtin."
+	echo "$(bold INFO:)  This script has been invoked using the 'source' builtin."
 	echo
 	alias exit="unalias exit; return"
 	fi
 
 # Check required packages
-if [[ ! -x $(which awk)  ]]; then caterr <<< "$(bold "ERROR:") 'awk' is not installed, but required for this script!" ; echo; exit 1; fi
-if [[ ! -x $(which tmux) ]]; then caterr <<< "$(bold "ERROR:") 'tmux' is not installed, but required for this script!"; echo; exit 1; fi
-if [[ ! -x $(which wget) ]]; then caterr <<< "$(bold "ERROR:") 'wget' is not installed, but required for this script!"; echo; exit 1; fi
-if [[ ! -x $(which tar)  ]]; then caterr <<< "$(bold "ERROR:") 'tar' is not installed, but required for this script!" ; echo; exit 1; fi
+if [[ ! -x $(which awk)  ]]; then caterr <<< "$(bold ERROR:) 'awk' is not installed, but required for this script!" ; echo; exit 1; fi
+if [[ ! -x $(which tmux) ]]; then caterr <<< "$(bold ERROR:) 'tmux' is not installed, but required for this script!"; echo; exit 1; fi
+if [[ ! -x $(which wget) ]]; then caterr <<< "$(bold ERROR:) 'wget' is not installed, but required for this script!"; echo; exit 1; fi
+if [[ ! -x $(which tar)  ]]; then caterr <<< "$(bold ERROR:) 'tar' is not installed, but required for this script!" ; echo; exit 1; fi
 
 # Get script filename and directory
 basename="$(basename "${BASH_SOURCE[0]}")"
@@ -462,7 +457,7 @@ unset basename dirname
 ############################### INCLUDE FUNCTIONS ################################
 
 if ! [[ -e "$THIS_DIR/helpers.sh" && -e "$THIS_DIR/setup.sh" ]]; then caterr <<-EOF
-	$(bold "ERROR:") The helper scripts for this program could not be found.
+	$(bold ERROR:) The helper scripts for this program could not be found.
 	       You can get the latest state and all files using
 	       'git clone https://github.com/dasisdormax/csgo-multiserver'
 	EOF
@@ -476,28 +471,28 @@ CFG=$(cfgfile)
 
 SUBSCRIPT_DIR="$THIS_DIR/scripts-$APPID"
 if [[ ! -d $SUBSCRIPT_DIR ]]; then caterr <<-EOF
-	$(bold "ERROR:") The subscript directory was not found at
+	$(bold ERROR:) The subscript directory was not found at
 	       $(bold "$SUBSCRIPT_DIR")!
 
 	EOF
 	exit 1; fi
 
 if [[ ! -r $SUBSCRIPT_DIR/instance.sh ]]; then caterr <<-EOF
-	$(bold "ERROR:") Instance creation script was not found at
+	$(bold ERROR:) Instance creation script was not found at
 	       $(bold "$SUBSCRIPT_DIR/instance.sh")!
 
 	EOF
 	exit 1; fi
 
 if [[ ! -r $SUBSCRIPT_DIR/permissions.sh ]]; then caterr <<-EOF
-	$(bold "ERROR:") Permission management script was not found at
+	$(bold ERROR:) Permission management script was not found at
 	       $(bold "$SUBSCRIPT_DIR/permissions.sh")!
 
 	EOF
 	exit 1; fi
 
 if [[ ! -r $SUBSCRIPT_DIR/server.conf ]]; then caterr <<-EOF
-		$(bold "ERROR:") Default server configuration file was not found at
+		$(bold ERROR:) Default server configuration file was not found at
 		       $(bold "$SUBSCRIPT_DIR/server.conf")!
 
 	EOF
@@ -587,7 +582,7 @@ while [[ $1 ]]; do
 			;;
 
 		( * )
-			caterr <<< "$(bold "ERROR:") Unrecognized Option: $(bold "$1")."
+			caterr <<< "$(bold ERROR:) Unrecognized Option: $(bold "$1")."
 			echo       "       Try '$THIS_COMM usage' for a list of available commands."
 			echo
 			exit 1
